/* One-off generator: writes the feature-section models into
   src/models/appModels/. Each file just hands a field spec to
   utils/featureSchema. Re-runnable (overwrites). Not required at runtime.

   Field spec here is intentionally lean — name / type / required / enum /
   default (what the Mongoose schema needs). The UI spec (labels, which
   columns show in the table, form grouping) lives in
   frontend/src/config/featureSections.js and MUST keep the same field
   names + enum values. */
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '..', 'src', 'models', 'appModels');

const S = (name, opts = {}) => ({ name, type: 'String', ...opts });
const N = (name, opts = {}) => ({ name, type: 'Number', ...opts });
const D = (name, opts = {}) => ({ name, type: 'Date', ...opts });
const B = (name, opts = {}) => ({ name, type: 'Boolean', default: false, ...opts });

const CURRENCY = ['INR', 'USD', 'EUR', 'GBP', 'AED'];
const DEPARTMENTS = ['Sales', 'Marketing', 'Operations', 'Engineering', 'HR', 'Finance', 'Support', 'Training', 'Admin'];

const MODELS = {
  // ======================= SALES =======================
  SalesDeal: [
    S('title', { required: true }),
    S('account'),
    S('contactName'),
    S('contactEmail'),
    S('contactPhone'),
    S('pipeline', { enum: ['Sales', 'Renewal', 'Upsell'], default: 'Sales' }),
    S('stage', {
      enum: ['Qualification', 'Needs Analysis', 'Proposal', 'Negotiation', 'Closed Won', 'Closed Lost'],
      default: 'Qualification',
    }),
    N('amount', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    N('probability', { default: 0 }),
    N('expectedRevenue', { default: 0 }),
    D('closeDate'),
    S('owner'),
    S('source', { enum: ['Website', 'Referral', 'Cold Call', 'Event', 'Partner', 'Ads', 'Other'], default: 'Other' }),
    S('competitors'),
    S('lossReason', { enum: ['', 'Price', 'Timing', 'Features', 'Competitor', 'No Budget', 'No Decision', 'Other'] }),
    S('nextStep'),
    D('lastActivityDate'),
    S('tags'),
    S('description'),
  ],
  SalesQuote: [
    S('number', { required: true }),
    S('title'),
    S('account'),
    S('contactName'),
    S('contactEmail'),
    S('deal'),
    S('status', { enum: ['Draft', 'Pending Approval', 'Sent', 'Accepted', 'Rejected', 'Expired'], default: 'Draft' }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    N('subtotal', { default: 0 }),
    N('discount', { default: 0 }),
    N('taxRate', { default: 0 }),
    N('total', { default: 0 }),
    D('issueDate'),
    D('validTill'),
    S('owner'),
    S('terms'),
    S('notes'),
  ],
  SalesOrder: [
    S('number', { required: true }),
    S('account'),
    S('quoteRef'),
    S('status', {
      enum: ['Draft', 'Confirmed', 'Processing', 'Fulfilled', 'Partially Fulfilled', 'Invoiced', 'Cancelled'],
      default: 'Draft',
    }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    N('subtotal', { default: 0 }),
    N('tax', { default: 0 }),
    N('shipping', { default: 0 }),
    N('total', { default: 0 }),
    D('orderDate'),
    D('expectedDelivery'),
    D('deliveredDate'),
    S('paymentStatus', { enum: ['Unpaid', 'Partial', 'Paid'], default: 'Unpaid' }),
    S('invoiceRef'),
    S('owner'),
    S('billingAddress'),
    S('shippingAddress'),
    S('notes'),
  ],
  Product: [
    S('name', { required: true }),
    S('sku'),
    S('category'),
    S('type', { enum: ['Service', 'Physical', 'Digital', 'Subscription'], default: 'Service' }),
    N('unitPrice', { default: 0 }),
    N('costPrice', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    N('taxRate', { default: 0 }),
    S('unit', { enum: ['Unit', 'Hour', 'Day', 'Month', 'Year', 'License', 'Seat'], default: 'Unit' }),
    S('billingCycle', { enum: ['One-time', 'Monthly', 'Quarterly', 'Yearly'], default: 'One-time' }),
    N('stockQty', { default: 0 }),
    N('reorderLevel', { default: 0 }),
    S('hsnCode'),
    S('status', { enum: ['Active', 'Inactive', 'Discontinued'], default: 'Active' }),
    S('description'),
  ],

  // ======================= MARKETING =======================
  Campaign: [
    S('name', { required: true }),
    S('type', {
      enum: ['Email', 'SMS', 'WhatsApp', 'Social', 'Paid Ads', 'Event', 'Webinar', 'Content', 'SEO'],
      default: 'Email',
    }),
    S('objective', { enum: ['Awareness', 'Lead Gen', 'Nurture', 'Conversion', 'Retention'], default: 'Lead Gen' }),
    S('status', { enum: ['Draft', 'Scheduled', 'Active', 'Paused', 'Completed', 'Cancelled'], default: 'Draft' }),
    D('startDate'),
    D('endDate'),
    N('budget', { default: 0 }),
    N('actualSpend', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    S('targetAudience'),
    N('expectedLeads', { default: 0 }),
    N('leads', { default: 0 }),
    N('conversions', { default: 0 }),
    N('revenue', { default: 0 }),
    S('owner'),
    S('utmSource'),
    S('utmMedium'),
    S('utmCampaign'),
    S('description'),
  ],
  EmailBroadcast: [
    S('name', { required: true }),
    S('channel', { enum: ['Email', 'SMS', 'WhatsApp'], default: 'Email' }),
    S('subject'),
    S('fromName'),
    S('fromAddress'),
    S('audience'),
    N('recipientCount', { default: 0 }),
    S('status', { enum: ['Draft', 'Scheduled', 'Sending', 'Sent', 'Paused', 'Failed'], default: 'Draft' }),
    D('scheduledAt'),
    D('sentAt'),
    N('sentCount', { default: 0 }),
    N('deliveredCount', { default: 0 }),
    N('openCount', { default: 0 }),
    N('clickCount', { default: 0 }),
    N('bounceCount', { default: 0 }),
    N('unsubscribeCount', { default: 0 }),
    S('templateRef'),
    B('abTest'),
    S('content'),
  ],
  Journey: [
    S('name', { required: true }),
    S('description'),
    S('triggerType', {
      enum: ['Form Submission', 'Tag Added', 'List Join', 'Field Change', 'Date Based', 'Page Visit', 'Manual'],
      default: 'Form Submission',
    }),
    S('triggerDetail'),
    S('status', { enum: ['Draft', 'Active', 'Paused', 'Archived'], default: 'Draft' }),
    S('goal'),
    N('steps', { default: 0 }),
    N('enrolled', { default: 0 }),
    N('inProgress', { default: 0 }),
    N('completed', { default: 0 }),
    N('goalMet', { default: 0 }),
    N('exitCount', { default: 0 }),
    S('owner'),
    D('startDate'),
    D('endDate'),
    S('notes'),
  ],
  Segment: [
    S('name', { required: true }),
    S('type', { enum: ['Dynamic', 'Static'], default: 'Dynamic' }),
    S('description'),
    S('criteria'),
    N('contactCount', { default: 0 }),
    N('marketableCount', { default: 0 }),
    N('usedInCount', { default: 0 }),
    S('source', { enum: ['CRM', 'Import', 'Form', 'Manual', 'Integration'], default: 'CRM' }),
    S('status', { enum: ['Active', 'Archived'], default: 'Active' }),
    D('lastRefreshed'),
    S('owner'),
    S('tags'),
  ],

  // ======================= OPERATIONS =======================
  OpsProject: [
    S('name', { required: true }),
    S('code'),
    S('client'),
    S('type', { enum: ['Implementation', 'Consulting', 'Support', 'Internal', 'Retainer'], default: 'Implementation' }),
    S('owner'),
    S('team'),
    S('priority', { enum: ['Low', 'Medium', 'High', 'Critical'], default: 'Medium' }),
    S('status', {
      enum: ['Planned', 'In Progress', 'On Hold', 'Blocked', 'Completed', 'Cancelled'],
      default: 'Planned',
    }),
    S('healthStatus', { enum: ['On Track', 'At Risk', 'Off Track'], default: 'On Track' }),
    N('progress', { default: 0 }),
    D('startDate'),
    D('dueDate'),
    D('completedDate'),
    N('budget', { default: 0 }),
    N('billedAmount', { default: 0 }),
    N('estimatedHours', { default: 0 }),
    N('loggedHours', { default: 0 }),
    S('description'),
  ],
  OpsDelivery: [
    S('engagement', { required: true }),
    S('client'),
    S('service'),
    S('stage', {
      enum: ['Kickoff', 'Discovery', 'Build', 'Review', 'UAT', 'Handover', 'Closed'],
      default: 'Kickoff',
    }),
    S('owner'),
    S('status', {
      enum: ['In Delivery', 'Awaiting Client', 'Blocked', 'On Hold', 'Delivered'],
      default: 'In Delivery',
    }),
    S('health', { enum: ['Green', 'Amber', 'Red'], default: 'Green' }),
    D('startDate'),
    D('eta'),
    D('deliveredDate'),
    B('signedOff'),
    N('cycleTimeDays', { default: 0 }),
    S('notes'),
  ],
  Vendor: [
    S('name', { required: true }),
    S('code'),
    S('category', {
      enum: ['IT & Software', 'Marketing', 'Facilities', 'Professional Services', 'Logistics', 'Other'],
      default: 'Other',
    }),
    S('contactPerson'),
    S('contactEmail'),
    S('contactPhone'),
    S('website'),
    S('address'),
    S('gstin'),
    S('paymentTerms', {
      enum: ['Net 15', 'Net 30', 'Net 45', 'Net 60', 'Advance', 'On Delivery'],
      default: 'Net 30',
    }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    N('rating', { default: 0 }),
    S('status', { enum: ['Active', 'Inactive', 'On Hold', 'Blacklisted'], default: 'Active' }),
    D('onboardedDate'),
    D('contractEnd'),
    S('notes'),
  ],
  OpsDocument: [
    S('title', { required: true }),
    S('type', {
      enum: ['Contract', 'MSA', 'NDA', 'SOW', 'Proposal', 'Invoice', 'Policy', 'Report', 'Other'],
      default: 'Other',
    }),
    S('category'),
    S('linkedType', { enum: ['Client', 'Vendor', 'Project', 'Employee', 'Deal', 'None'], default: 'None' }),
    S('linkedTo'),
    S('owner'),
    S('status', {
      enum: ['Draft', 'In Review', 'Pending Signature', 'Signed', 'Active', 'Expired', 'Terminated'],
      default: 'Draft',
    }),
    S('confidentiality', { enum: ['Public', 'Internal', 'Confidential', 'Restricted'], default: 'Internal' }),
    S('version'),
    D('effectiveDate'),
    D('expiryDate'),
    D('renewalReminderDate'),
    S('fileUrl'),
    S('notes'),
  ],
  Approval: [
    S('title', { required: true }),
    S('type', {
      enum: ['Discount', 'Purchase Order', 'Expense', 'Leave', 'Budget', 'Contract', 'Hiring', 'Other'],
      default: 'Other',
    }),
    S('requestedBy'),
    S('department', { enum: DEPARTMENTS }),
    N('amount', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    S('priority', { enum: ['Low', 'Normal', 'High', 'Urgent'], default: 'Normal' }),
    S('currentStage'),
    S('approver'),
    S('status', { enum: ['Draft', 'Pending', 'In Review', 'Approved', 'Rejected', 'Withdrawn'], default: 'Pending' }),
    D('requestedDate'),
    D('dueDate'),
    D('decisionDate'),
    S('justification'),
    S('decisionNote'),
  ],

  // ======================= LMS =======================
  Course: [
    S('title', { required: true }),
    S('code'),
    S('category', {
      enum: ['Aptitude', 'Technical', 'Communication', 'Interview Prep', 'Domain', 'Soft Skills', 'Certification'],
      default: 'Technical',
    }),
    S('level', { enum: ['Beginner', 'Intermediate', 'Advanced'], default: 'Beginner' }),
    S('mode', { enum: ['Self-paced', 'Cohort', 'Live', 'Blended'], default: 'Cohort' }),
    S('language', { enum: ['English', 'Hindi', 'Bilingual'], default: 'English' }),
    N('durationHours', { default: 0 }),
    N('modules', { default: 0 }),
    N('lessons', { default: 0 }),
    N('price', { default: 0 }),
    N('discountPrice', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    S('instructor'),
    S('status', { enum: ['Draft', 'Published', 'Archived'], default: 'Draft' }),
    D('publishedDate'),
    N('rating', { default: 0 }),
    N('enrolledCount', { default: 0 }),
    S('thumbnailUrl'),
    S('prerequisites'),
    S('outcomes'),
    S('description'),
  ],
  Batch: [
    S('name', { required: true }),
    S('code'),
    S('course'),
    S('mode', { enum: ['Online', 'Offline', 'Hybrid'], default: 'Online' }),
    S('trainer'),
    S('coordinator'),
    D('startDate'),
    D('endDate'),
    S('schedule'),
    N('seats', { default: 0 }),
    N('enrolled', { default: 0 }),
    N('waitlist', { default: 0 }),
    S('status', {
      enum: ['Planned', 'Open for Enrollment', 'Running', 'Completed', 'Cancelled'],
      default: 'Planned',
    }),
    N('completionRate', { default: 0 }),
    S('venue'),
    S('meetingLink'),
    S('notes'),
  ],
  Student: [
    S('name', { required: true }),
    S('email'),
    S('phone'),
    S('altPhone'),
    S('city'),
    S('course'),
    S('batch'),
    S('enrollmentId'),
    D('enrolledOn'),
    S('status', { enum: ['Active', 'On Hold', 'Completed', 'Dropped', 'Deferred'], default: 'Active' }),
    N('progress', { default: 0 }),
    N('attendancePct', { default: 0 }),
    N('avgScore', { default: 0 }),
    N('feeTotal', { default: 0 }),
    N('feePaid', { default: 0 }),
    S('feeStatus', { enum: ['Paid', 'Partial', 'Unpaid', 'Waived'], default: 'Unpaid' }),
    S('source', { enum: ['Website', 'Referral', 'Walk-in', 'Ads', 'Counselor', 'Partner'], default: 'Website' }),
    S('counselor'),
    S('guardianName'),
    S('guardianPhone'),
    S('notes'),
  ],
  LiveClass: [
    S('topic', { required: true }),
    S('course'),
    S('batch'),
    S('trainer'),
    D('scheduledAt'),
    N('durationMin', { default: 60 }),
    S('mode', { enum: ['Zoom', 'Google Meet', 'MS Teams', 'In-person'], default: 'Zoom' }),
    S('joinUrl'),
    S('status', {
      enum: ['Scheduled', 'Live', 'Completed', 'Cancelled', 'Rescheduled'],
      default: 'Scheduled',
    }),
    N('registeredCount', { default: 0 }),
    N('attendedCount', { default: 0 }),
    S('recordingUrl'),
    S('materialsUrl'),
    S('agenda'),
    S('notes'),
  ],
  AttendanceRecord: [
    S('student', { required: true }),
    S('batch'),
    S('course'),
    S('sessionTopic'),
    D('date'),
    S('status', { enum: ['Present', 'Absent', 'Late', 'Left Early', 'Excused'], default: 'Present' }),
    S('joinTime'),
    S('leaveTime'),
    N('durationMin', { default: 0 }),
    S('markedBy', { enum: ['Auto', 'Manual'], default: 'Manual' }),
    S('remarks'),
  ],
  Certificate: [
    S('student', { required: true }),
    S('course'),
    S('batch'),
    S('certificateId'),
    S('title'),
    S('type', { enum: ['Completion', 'Participation', 'Merit', 'Achievement'], default: 'Completion' }),
    D('issuedOn'),
    D('validUntil'),
    S('grade'),
    N('score', { default: 0 }),
    S('status', { enum: ['Draft', 'Issued', 'Sent', 'Revoked'], default: 'Draft' }),
    S('verificationUrl'),
    S('issuedBy'),
    S('notes'),
  ],

  // ======================= HR =======================
  Employee: [
    S('name', { required: true }),
    S('employeeId'),
    S('email'),
    S('phone'),
    S('personalEmail'),
    S('department', { enum: DEPARTMENTS }),
    S('designation'),
    S('reportingManager'),
    S('employmentType', {
      enum: ['Permanent', 'Contract', 'Probation', 'Intern', 'Consultant'],
      default: 'Permanent',
    }),
    S('workLocation', { enum: ['Office', 'Remote', 'Hybrid'], default: 'Office' }),
    D('dateOfJoining'),
    D('dateOfBirth'),
    S('gender', { enum: ['Male', 'Female', 'Other', 'Prefer not to say'] }),
    S('status', {
      enum: ['Active', 'On Leave', 'Notice Period', 'Suspended', 'Resigned', 'Terminated'],
      default: 'Active',
    }),
    N('ctc', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    S('bankAccount'),
    S('pan'),
    S('uan'),
    S('emergencyContactName'),
    S('emergencyContactPhone'),
    S('address'),
    S('skills'),
  ],
  Candidate: [
    S('name', { required: true }),
    S('email'),
    S('phone'),
    S('role'),
    S('department', { enum: DEPARTMENTS }),
    S('stage', {
      enum: ['Applied', 'Screening', 'Shortlisted', 'Interview', 'Assessment', 'Offer', 'Hired', 'Rejected', 'On Hold', 'Withdrawn'],
      default: 'Applied',
    }),
    S('source', {
      enum: ['Job Portal', 'Referral', 'LinkedIn', 'Career Page', 'Agency', 'Walk-in', 'Campus'],
      default: 'Job Portal',
    }),
    S('currentCompany'),
    N('currentCtc', { default: 0 }),
    N('expectedCtc', { default: 0 }),
    N('noticePeriodDays', { default: 0 }),
    N('experienceYears', { default: 0 }),
    S('location'),
    D('appliedOn'),
    D('interviewDate'),
    S('recruiter'),
    N('rating', { default: 0 }),
    S('resumeUrl'),
    S('feedback'),
  ],
  HrAttendance: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    D('date'),
    S('shift', { enum: ['General', 'Morning', 'Evening', 'Night', 'Flexible'], default: 'General' }),
    S('clockIn'),
    S('clockOut'),
    N('workedHours', { default: 0 }),
    N('overtimeHours', { default: 0 }),
    S('status', {
      enum: ['Present', 'Absent', 'Half Day', 'Work From Home', 'On Leave', 'Holiday', 'Weekend'],
      default: 'Present',
    }),
    N('lateByMin', { default: 0 }),
    S('location'),
    B('regularized'),
    S('remarks'),
  ],
  LeaveRequest: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('leaveType', {
      enum: ['Casual', 'Sick', 'Earned', 'Unpaid', 'Comp Off', 'Maternity', 'Paternity', 'Bereavement'],
      default: 'Casual',
    }),
    D('fromDate'),
    D('toDate'),
    N('days', { default: 1 }),
    B('halfDay'),
    S('reason'),
    S('status', { enum: ['Pending', 'Approved', 'Rejected', 'Cancelled', 'Withdrawn'], default: 'Pending' }),
    S('approver'),
    D('appliedOn'),
    D('decisionDate'),
    S('contactDuringLeave'),
    S('handoverTo'),
    S('decisionNote'),
  ],
  Payslip: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('payPeriod'),
    D('payDate'),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    N('ctc', { default: 0 }),
    N('basic', { default: 0 }),
    N('hra', { default: 0 }),
    N('allowances', { default: 0 }),
    N('grossEarnings', { default: 0 }),
    N('pf', { default: 0 }),
    N('esi', { default: 0 }),
    N('tds', { default: 0 }),
    N('otherDeductions', { default: 0 }),
    N('totalDeductions', { default: 0 }),
    N('netPay', { default: 0 }),
    N('paidDays', { default: 0 }),
    N('lopDays', { default: 0 }),
    S('status', { enum: ['Draft', 'Processed', 'Paid', 'On Hold'], default: 'Draft' }),
    S('paymentMode', { enum: ['Bank Transfer', 'Cheque', 'Cash', 'UPI'], default: 'Bank Transfer' }),
    S('notes'),
  ],
  Appraisal: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('cycle'),
    D('reviewPeriodStart'),
    D('reviewPeriodEnd'),
    S('manager'),
    S('reviewer'),
    N('selfRating', { default: 0 }),
    N('managerRating', { default: 0 }),
    N('finalRating', { default: 0 }),
    S('ratingLabel', {
      enum: ['', 'Outstanding', 'Exceeds Expectations', 'Meets Expectations', 'Needs Improvement', 'Unsatisfactory'],
    }),
    S('status', {
      enum: ['Not Started', 'Self Review', 'Manager Review', 'Calibration', 'Completed', 'Acknowledged'],
      default: 'Not Started',
    }),
    B('promotionRecommended'),
    N('incrementPct', { default: 0 }),
    S('goals'),
    S('strengths'),
    S('improvements'),
    S('managerComments'),
  ],
  HrOnboarding: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('designation'),
    S('manager'),
    S('buddy'),
    D('joiningDate'),
    D('dueDate'),
    S('status', { enum: ['Not Started', 'In Progress', 'Completed', 'Delayed'], default: 'Not Started' }),
    N('progress', { default: 0 }),
    B('docsCollected'),
    B('itSetupDone'),
    B('assetsIssued'),
    B('accessGranted'),
    B('inductionDone'),
    S('notes'),
  ],
  Timesheet: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('project'),
    S('task'),
    D('date'),
    S('weekOf'),
    N('hours', { default: 0 }),
    B('billable'),
    S('status', { enum: ['Draft', 'Submitted', 'Approved', 'Rejected'], default: 'Draft' }),
    S('approver'),
    S('description'),
  ],
  ShiftRoster: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('shiftName', { enum: ['General', 'Morning', 'Evening', 'Night', 'Split'], default: 'General' }),
    S('startTime'),
    S('endTime'),
    S('weekOff'),
    D('fromDate'),
    D('toDate'),
    S('location'),
    S('status', { enum: ['Scheduled', 'Active', 'Swapped', 'Cancelled'], default: 'Scheduled' }),
    S('notes'),
  ],
  Holiday: [
    S('name', { required: true }),
    D('date'),
    S('type', { enum: ['National', 'Regional', 'Restricted', 'Company'], default: 'National' }),
    S('day'),
    S('applicableLocations'),
    B('optional'),
    N('year', { default: 0 }),
    S('description'),
  ],
  ExpenseClaim: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('category', {
      enum: ['Travel', 'Food', 'Accommodation', 'Fuel', 'Office Supplies', 'Client Entertainment', 'Training', 'Other'],
      default: 'Travel',
    }),
    S('title'),
    N('amount', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    D('expenseDate'),
    D('claimDate'),
    S('status', { enum: ['Draft', 'Submitted', 'Approved', 'Rejected', 'Reimbursed'], default: 'Draft' }),
    S('approver'),
    D('paymentDate'),
    S('receiptUrl'),
    S('notes'),
  ],
  LoanAdvance: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('type', {
      enum: ['Salary Advance', 'Personal Loan', 'Emergency Loan', 'Travel Advance'],
      default: 'Salary Advance',
    }),
    N('amount', { default: 0 }),
    S('currency', { enum: CURRENCY, default: 'INR' }),
    D('requestDate'),
    S('reason'),
    N('tenureMonths', { default: 0 }),
    N('emi', { default: 0 }),
    N('outstanding', { default: 0 }),
    S('status', {
      enum: ['Requested', 'Approved', 'Disbursed', 'Repaying', 'Closed', 'Rejected'],
      default: 'Requested',
    }),
    S('approver'),
    D('disbursedDate'),
    S('notes'),
  ],
  TrainingProgram: [
    S('title', { required: true }),
    S('category', {
      enum: ['Onboarding', 'Compliance', 'Technical', 'Leadership', 'Soft Skills', 'Product', 'Safety'],
      default: 'Technical',
    }),
    S('mode', { enum: ['Online', 'Classroom', 'Workshop', 'Self-paced', 'External'], default: 'Online' }),
    S('trainer'),
    S('audience'),
    D('startDate'),
    D('endDate'),
    N('durationHours', { default: 0 }),
    N('seats', { default: 0 }),
    N('enrolled', { default: 0 }),
    N('completed', { default: 0 }),
    N('completionRate', { default: 0 }),
    S('status', { enum: ['Planned', 'Open', 'Running', 'Completed', 'Cancelled'], default: 'Planned' }),
    B('mandatory'),
    N('cost', { default: 0 }),
    S('notes'),
  ],
  HrAsset: [
    S('assetTag', { required: true }),
    S('category', {
      enum: ['Laptop', 'Desktop', 'Monitor', 'Phone', 'SIM', 'Access Card', 'Headset', 'Furniture', 'Software License', 'Other'],
      default: 'Laptop',
    }),
    S('model'),
    S('serialNumber'),
    S('assignedTo'),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    D('issueDate'),
    D('returnDate'),
    S('condition', { enum: ['New', 'Good', 'Fair', 'Damaged', 'Retired'], default: 'Good' }),
    S('status', { enum: ['In Stock', 'Assigned', 'In Repair', 'Retired', 'Lost'], default: 'In Stock' }),
    N('value', { default: 0 }),
    S('notes'),
  ],
  HrDocument: [
    S('employee', { required: true }),
    S('employeeId'),
    S('docType', {
      enum: ['Offer Letter', 'Appointment Letter', 'Contract', 'ID Proof', 'Address Proof', 'PAN', 'Aadhaar', 'Educational', 'Experience', 'Relieving Letter', 'Payslip', 'Other'],
      default: 'Other',
    }),
    S('title'),
    S('fileUrl'),
    D('issueDate'),
    D('expiryDate'),
    S('status', { enum: ['Pending', 'Received', 'Verified', 'Rejected', 'Expired'], default: 'Pending' }),
    B('confidential'),
    S('uploadedBy'),
    S('notes'),
  ],
  HrTicket: [
    S('raisedBy', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('category', {
      enum: ['Payroll', 'Leave', 'Attendance', 'Benefits', 'IT Access', 'Facilities', 'Grievance', 'Policy', 'Other'],
      default: 'Other',
    }),
    S('subject'),
    S('priority', { enum: ['Low', 'Normal', 'High', 'Urgent'], default: 'Normal' }),
    S('status', { enum: ['Open', 'In Progress', 'On Hold', 'Resolved', 'Closed'], default: 'Open' }),
    S('assignedTo'),
    D('raisedOn'),
    D('resolvedOn'),
    S('description'),
    S('resolution'),
  ],
  Announcement: [
    S('title', { required: true }),
    S('category', {
      enum: ['General', 'Policy', 'Event', 'Holiday', 'Payroll', 'Benefits', 'Emergency', 'Celebration'],
      default: 'General',
    }),
    S('audience'),
    S('publishedBy'),
    D('publishDate'),
    D('expiryDate'),
    S('status', { enum: ['Draft', 'Scheduled', 'Published', 'Archived'], default: 'Draft' }),
    B('pinned'),
    B('acknowledgementRequired'),
    N('readCount', { default: 0 }),
    S('body'),
  ],
  Recognition: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('awardType', {
      enum: ['Employee of the Month', 'Spot Award', 'Team Award', 'Long Service', 'Values Champion', 'Peer Recognition'],
      default: 'Spot Award',
    }),
    S('givenBy'),
    D('date'),
    N('points', { default: 0 }),
    S('reason'),
    S('status', { enum: ['Nominated', 'Approved', 'Awarded', 'Rejected'], default: 'Nominated' }),
    S('visibility', { enum: ['Public', 'Team', 'Private'], default: 'Public' }),
  ],
  ExitRecord: [
    S('employee', { required: true }),
    S('employeeId'),
    S('department', { enum: DEPARTMENTS }),
    S('designation'),
    S('exitType', {
      enum: ['Resignation', 'Termination', 'Retirement', 'End of Contract', 'Absconding'],
      default: 'Resignation',
    }),
    D('resignationDate'),
    D('lastWorkingDay'),
    N('noticePeriodServedDays', { default: 0 }),
    S('reason', {
      enum: ['Better Opportunity', 'Compensation', 'Relocation', 'Personal', 'Higher Studies', 'Work Environment', 'Performance', 'Other'],
      default: 'Other',
    }),
    S('status', {
      enum: ['Initiated', 'Notice Period', 'Clearance Pending', 'Exit Interview', 'FnF Pending', 'Completed'],
      default: 'Initiated',
    }),
    B('clearanceIT'),
    B('clearanceFinance'),
    B('clearanceHR'),
    B('clearanceManager'),
    B('exitInterviewDone'),
    N('fnfAmount', { default: 0 }),
    D('fnfSettledDate'),
    B('rehireEligible'),
    S('notes'),
  ],

  // ======================= MESSENGER =======================
  MessengerContact: [
    S('name', { required: true }),
    S('phone'),
    S('email'),
    S('company'),
    B('whatsappOptIn'),
    B('smsOptIn'),
    B('emailOptIn'),
    S('consent', { enum: ['Opted-in', 'Opted-out', 'Pending', 'Unknown'], default: 'Unknown' }),
    D('consentDate'),
    S('tags'),
    S('lifecycleStage', { enum: ['Lead', 'Prospect', 'Customer', 'Churned'], default: 'Lead' }),
    S('owner'),
    D('lastContactedAt'),
    S('lastChannel', { enum: ['', 'WhatsApp', 'SMS', 'Email', 'Call'] }),
    S('source', {
      enum: ['Manual', 'Import', 'Web Form', 'CRM Sync', 'Inbound Message'],
      default: 'Manual',
    }),
    S('notes'),
  ],
  MessengerConversation: [
    S('contact', { required: true }),
    S('channel', { enum: ['WhatsApp', 'SMS', 'Email'], default: 'WhatsApp' }),
    S('handle'),
    S('subject'),
    S('assignedTo'),
    S('team'),
    S('status', { enum: ['Open', 'Pending', 'Snoozed', 'Resolved', 'Closed'], default: 'Open' }),
    S('priority', { enum: ['Low', 'Normal', 'High', 'Urgent'], default: 'Normal' }),
    S('lastMessage'),
    D('lastMessageAt'),
    S('lastDirection', { enum: ['', 'Inbound', 'Outbound'] }),
    N('unreadCount', { default: 0 }),
    N('messageCount', { default: 0 }),
    N('firstResponseMin', { default: 0 }),
    S('tags'),
    B('withinWindow'),
    S('notes'),
  ],
  MessengerBroadcast: [
    S('name', { required: true }),
    S('channel', { enum: ['WhatsApp', 'SMS', 'Email'], default: 'WhatsApp' }),
    S('templateRef'),
    S('audience'),
    N('recipientCount', { default: 0 }),
    S('status', {
      enum: ['Draft', 'Scheduled', 'Sending', 'Sent', 'Paused', 'Failed', 'Cancelled'],
      default: 'Draft',
    }),
    D('scheduledAt'),
    D('sentAt'),
    N('sentCount', { default: 0 }),
    N('deliveredCount', { default: 0 }),
    N('readCount', { default: 0 }),
    N('replyCount', { default: 0 }),
    N('failedCount', { default: 0 }),
    N('throttlePerMin', { default: 0 }),
    S('owner'),
    S('message'),
    S('notes'),
  ],
};

const fmtField = (f) => {
  const parts = [`type: '${f.type}'`];
  if (f.required) parts.push('required: true');
  if (f.enum) parts.push(`enum: ${JSON.stringify(f.enum)}`);
  if (f.default !== undefined) parts.push(`default: ${JSON.stringify(f.default)}`);
  return `    { name: '${f.name}', ${parts.join(', ')} },`;
};

let written = 0;
for (const [model, fields] of Object.entries(MODELS)) {
  const body = `const mongoose = require('mongoose');
const { featureSchema } = require('../utils/featureSchema');

// Auto-CRUD model for a feature-section tab — list/create/update/delete come
// from the generic controller. Field spec mirrors config/featureSections.js.
module.exports = mongoose.model(
  '${model}',
  featureSchema([
${fields.map(fmtField).join('\n')}
  ])
);
`;
  fs.writeFileSync(path.join(OUT, `${model}.js`), body);
  written++;
}
console.log(`wrote ${written} models to ${OUT}`);
